# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DTmaIJCAFDAgCwRBgXQI50u1nb7v7df3
"""

print("Hello World")

print("Pavan Singh")

